version: '2.1'
services:
  app:
    build: .
    environment: 
      ALLOWED_HOSTS: send,localhost
      SECRET_KEY: zlk5yl*t+duw^*a2dj%kv3v5g-hpo-38+c(safh2nvzpxu3c2o
      DATABASE_URL: sqlite:///database/db.sqlite3
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - ./database:/app/database
