version: '2.1'
services:
  app:
    build: .
    environment: 
      ALLOWED_HOSTS: send,localhost
      DATABASE_URL: sqlite:////database/db.sqlite3
      SECRET_KEY: "zlk5yl*t+duw^*a2dj%kv3v5g-hpo-38+c(safh2nvzpxu3c2o"
      DEBUG: true
    ports:
      - 8080:8080
    volumes:
      - database:/database/
volumes:
  database: {}