version: '2.1'
services:
  app:
    build: .
    environment: 
      ALLOWED_HOSTS: send,127.0.0.1
      SECRET_KEY: zlk5yl*t+duw^*a2dj%kv3v5g-hpo-38+c(safh2nvzpxu3c2o
      DATABASE_URL: sqlite:///database/prod-local.sqlite3
    ports:
      - 8080:8080
    volumes:
      - database:/app/database
volumes:
  database: {}