# Generated by Django 4.0.1 on 2022-01-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('max_downloads', models.IntegerField()),
                ('expire_date', models.DateTimeField()),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.upload')),
            ],
        ),
    ]
