# Generated by Django 4.0.1 on 2022-01-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='upload_id',
            new_name='upload',
        ),
    ]
