# Generated by Django 4.0.1 on 2022-01-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_rename_upload_id_download_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='upload_path',
            new_name='file_name',
        ),
    ]
